# Generated by Django 3.2.4 on 2021-10-25 07:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('dob', models.DateField(null=True)),
                ('image', models.ImageField(default='default.jpg', upload_to='')),
                ('role', models.CharField(choices=[('Ad', 'Admin'), ('It', 'IT staff'), ('Mt', 'Maintenance'), ('Mg', 'Manager'), ('Rc', 'Room caretaker'), ('Sv', 'Supervisor')], max_length=2)),
                ('local_user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shortname', models.CharField(max_length=30)),
                ('fullname', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('level', models.IntegerField()),
                ('room_type', models.CharField(choices=[('Cr', 'Class room'), ('Mr', 'Meeting room'), ('Os', 'Office space'), ('Oth', 'Other')], max_length=30)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sci_dashboard_app.building')),
                ('caretaker', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sci_dashboard_app.account')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reportID', models.CharField(max_length=30)),
                ('room', models.CharField(max_length=100, null=True)),
                ('creatorname', models.CharField(max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('statusReport', models.CharField(choices=[('S', 'success'), ('R', 'received'), ('P', 'pending'), ('St', 'start')], max_length=50)),
                ('description', models.TextField()),
                ('image', models.TextField()),
                ('typeReport', models.CharField(choices=[('Net', 'internet'), ('Teach', 'teaching materials'), ('Elec', 'electrical system'), ('Water', 'water supply system'), ('Phone', 'phone system'), ('Air', 'air conditioning system'), ('Room', 'room material'), ('Clean', 'cleanliness and safety'), ('Env', 'building and environment'), ('Oth', 'other')], max_length=50)),
                ('lastModified', models.DateTimeField(auto_now=True)),
                ('building', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sci_dashboard_app.building')),
                ('takecareBy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sci_dashboard_app.account')),
            ],
        ),
    ]
