# Generated by Django 3.2.4 on 2021-10-25 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sci_dashboard_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='image',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='lastModified',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
