# Generated by Django 3.2.4 on 2021-11-05 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sci_dashboard_app', '0002_auto_20211025_1441'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reportType', models.CharField(max_length=30)),
            ],
        ),
        migrations.RemoveField(
            model_name='report',
            name='typeReport',
        ),
        migrations.AddField(
            model_name='report',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sci_dashboard_app.reporttype'),
        ),
    ]
