# Generated by Django 3.2.4 on 2021-11-21 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sci_dashboard_app', '0003_auto_20211105_1959'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporttype',
            name='labels',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
